# Generated by Django 5.2.8 on 2025-11-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("player", "Player"), ("dm", "Dungeon Master")],
                default="player",
                max_length=10,
            ),
        ),
    ]
