# Generated by Django 5.2.8 on 2025-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.JSONField(default=list),
        ),
    ]
