# Generated by Django 5.0 on 2025-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_remove_userprofile_role_userprofile_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_contact",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("sms", "SMS"), ("discord", "Discord")],
                default="",
                help_text="Preferred method for game notifications",
                max_length=10,
            ),
        ),
    ]
