# Generated by Django 6.0 on 2025-12-11 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0005_userprofile_preferred_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="savedcharacter",
            index=models.Index(
                fields=["user", "-updated_at"], name="generator_s_user_id_62b2a7_idx"
            ),
        ),
    ]
