# Generated by Django 6.0 on 2025-12-13 23:05

from django.db import migrations


def create_test_user(apps, schema_editor):
    """Create test user 'sam' with password 'pass' and all roles."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('generator', 'UserProfile')

    # Create or update user
    user, created = User.objects.get_or_create(
        username='sam',
        defaults={
            'is_superuser': True,
            'is_staff': True,
        }
    )
    if not created:
        user.is_superuser = True
        user.is_staff = True

    # Set password (using Django's make_password since set_password isn't available in migrations)
    from django.contrib.auth.hashers import make_password
    user.password = make_password('pass')
    user.save()

    # Create or update profile with all roles
    profile, _ = UserProfile.objects.get_or_create(user=user)
    profile.roles = ['admin', 'dm', 'player']
    profile.save()


def reverse_test_user(apps, schema_editor):
    """Remove test user 'sam'."""
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='sam').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0007_add_usernotes"),
    ]

    operations = [
        migrations.RunPython(create_test_user, reverse_test_user),
    ]
