# Generated by Django 6.0 on 2025-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0008_migrate_skill_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcharacter",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
