# Generated by Django 6.0 on 2025-12-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0009_savedcharacter_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcharacter",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedcharacter",
            name="race",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
