# Generated by Django 5.2.8 on 2026-01-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0010_savedcharacter_age_savedcharacter_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcharacter",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
