"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT VARIABLE HELPERS
# =============================================================================


def parse_bool_env(key: str, default: bool = False) -> bool:
    """
    Parse boolean environment variable with validation.

    Accepts: true, 1, yes, false, 0, no (case-insensitive)
    Empty string or missing variable returns the default.
    """
    value = os.environ.get(key, "").strip().lower()
    if not value:
        return default
    if value in ("true", "1", "yes"):
        return True
    if value in ("false", "0", "no"):
        return False
    raise ImproperlyConfigured(
        f"{key} must be a boolean value (true/false, 1/0, yes/no), got '{value}'"
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_bool_env("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# In production, DJANGO_SECRET_KEY must be set. In debug mode, use an insecure default.
_secret_key = os.environ.get("DJANGO_SECRET_KEY")
if not _secret_key:
    if DEBUG:
        _secret_key = "django-insecure-dev-only-key-do-not-use-in-production"
    else:
        raise ValueError(
            "DJANGO_SECRET_KEY environment variable is required in production. "
            "Set DJANGO_DEBUG=True for development mode."
        )
SECRET_KEY = _secret_key

# Allowed hosts from environment or defaults for development
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,192.168.4.163"
    ).split(",")
    if h.strip()
]

# Validate ALLOWED_HOSTS in production
if not DEBUG and (not ALLOWED_HOSTS or ALLOWED_HOSTS == [""]):
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must be set in production. "
        "Set to comma-separated hostnames/IPs that can serve this site."
    )

# CSRF trusted origins for form submissions (required for Django 4.0+)
# Format: http://domain:port or https://domain:port
_default_csrf_origins = []
for host in ALLOWED_HOSTS:
    # Add common ports for each allowed host
    for port in ["8000", "8765", "9066"]:
        _default_csrf_origins.append(f"http://{host}:{port}")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS", ",".join(_default_csrf_origins)
    ).split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "webapp.generator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "webapp.generator.middleware.ContentNegotiationMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "webapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "webapp.generator.context_processors.git_info",
            ],
        },
    },
]

WSGI_APPLICATION = "webapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Parse DATABASE_URL for PostgreSQL using urllib.parse
    # This correctly handles special characters in passwords
    # Format: postgres://user:password@host:port/dbname
    from urllib.parse import urlparse

    db_url = urlparse(DATABASE_URL.replace("postgres://", "postgresql://"))
    if db_url.scheme == "postgresql" and db_url.hostname:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": db_url.path.lstrip("/"),
                "USER": db_url.username or "",
                "PASSWORD": db_url.password or "",
                "HOST": db_url.hostname,
                "PORT": str(db_url.port) if db_url.port else "5432",
            }
        }
    else:
        raise ValueError(f"Invalid DATABASE_URL format: {DATABASE_URL}")
else:
    # Default to SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        },
        {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
        {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
        {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
    ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / ".." / "references",
]

# References images directory (for handbook/markdown images)
REFERENCES_IMAGES_DIR = BASE_DIR / ".." / "references" / "images"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "welcome"
LOGOUT_REDIRECT_URL = "welcome"

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Only enable secure cookies if using HTTPS
    # Set DJANGO_USE_HTTPS=True in .env if you have SSL/TLS configured
    USE_HTTPS = parse_bool_env("DJANGO_USE_HTTPS", default=False)
    if USE_HTTPS:
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True
    else:
        CSRF_COOKIE_SECURE = False
        SESSION_COOKIE_SECURE = False
        # Allow CSRF cookies to work on HTTP for development/testing
        CSRF_COOKIE_SAMESITE = "Lax"
        SESSION_COOKIE_SAMESITE = "Lax"
